In [4]:
import pandas as pd 
df2 = pd.read_csv("https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-abbrevs.csv")
df1 = pd.read_csv("https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-population.csv")

print(df1)
print(df2)

result = pd.concat([df2, df1], sort = False)
#print(df1)
#print(df2)
new = pd.merge(df1, df2, left_on='state/region', right_on="abbreviation", how = 'outer')
clean = new.drop('abbreviation', axis=1)

print (df1['state/region'].dtype)
print (df2['abbreviation'].dtype)

#print(new)
#print(clean)

     state/region     ages  year   population
0              AL  under18  2012    1117489.0
1              AL    total  2012    4817528.0
2              AL  under18  2010    1130966.0
3              AL    total  2010    4785570.0
4              AL  under18  2011    1125763.0
...           ...      ...   ...          ...
2539          USA    total  2010  309326295.0
2540          USA  under18  2011   73902222.0
2541          USA    total  2011  311582564.0
2542          USA  under18  2012   73708179.0
2543          USA    total  2012  313873685.0

[2544 rows x 4 columns]
                   state abbreviation
0                Alabama           AL
1                 Alaska           AK
2                Arizona           AZ
3               Arkansas           AR
4             California           CA
5               Colorado           CO
6            Connecticut           CT
7               Delaware           DE
8   District of Columbia           DC
9                Florida           FL
10               Georgia           GA
11                Hawaii           HI
12                 Idaho           ID
13              Illinois           IL
14               Indiana           IN
15                  Iowa           IA
16                Kansas           KS
17              Kentucky           KY
18             Louisiana           LA
19                 Maine           ME
20               Montana           MT
21              Nebraska           NE
22                Nevada           NV
23         New Hampshire           NH
24            New Jersey           NJ
25            New Mexico           NM
26              New York           NY
27        North Carolina           NC
28          North Dakota           ND
29                  Ohio           OH
30              Oklahoma           OK
31                Oregon           OR
32              Maryland           MD
33         Massachusetts           MA
34              Michigan           MI
35             Minnesota           MN
36           Mississippi           MS
37              Missouri           MO
38          Pennsylvania           PA
39          Rhode Island           RI
40        South Carolina           SC
41          South Dakota           SD
42             Tennessee           TN
43                 Texas           TX
44                  Utah           UT
45               Vermont           VT
46              Virginia           VA
47            Washington           WA
48         West Virginia           WV
49             Wisconsin           WI
50               Wyoming           WY
object
object

In [14]:
import pandas as pd

# Data Ingestion

## Merge the Data Set

df1 = pd.read_csv("../Projects/Project2/data/id-hw-exams.csv", converters={"SID": str.lower})
df2 = pd.read_csv("../Projects/Project2/data/id-section.csv", converters = {"Email Address": str.lower, "NetID": str.lower} )

merged_set= pd.merge(df1, df2, left_on = 'SID', right_on = 'NetID')

#print(merged_set['NetID'])
#print(merged_set)

cleaned_set = merged_set.drop(columns = ['NetID'])

print(cleaned_set)

## Drop the Timestamp Columns for Homeworks and Exams

#timestamps = cleaned_set.filter(regex=r"\W*(Submission)\W*", axis=1)

#timestamps = cleaned_set.filter(regex=r"\W*(Submission)\W*", axis=1)

#print(timestamps)

for num in range (1,11):
    cleaned_set[f'hw{num}_score'] = ((cleaned_set[f'Homework {num}'] / cleaned_set[f'Homework {num} - Max Points'])*100)

for num in range (1,4):
    cleaned_set[f'exam{num}_score'] = ((cleaned_set[f'Exam {num}'] / cleaned_set[f'Exam {num} - Max Points'])*100)


homework_scores = cleaned_set.filter(regex=r"^hw", axis=1)

#print(homework_scores)

cleaned_set['hw_avg'] = homework_scores.mean(axis=1)

#print(homework_scores.mean(axis=1))

exam_scores = cleaned_set.filter(regex=r"^ex", axis=1)

cleaned_set['ex_avg'] = exam_scores.mean(axis=1)

#cleaned_set = cleaned_set.drop(timestamps, axis = 1)

#cleaned_set = cleaned_set.fillna(0)

#cleaned_set

for num in range (1,11):
    cleaned_set.drop(cleaned_set[f'Homework {num}'], axis = 1)
    cleaned_set.drop(cleaned_set[f'Homework {num} - Max Points'], axis = 1)

for num in range (1,4):
    cleaned_set.drop(cleaned_set[f'Exam {num}'], axis = 1)
    cleaned_set.drop(cleaned_set[f'Exam {num} - Max Points'], axis = 1)

    First Name   Last Name       SID  Homework 1  Homework 1 - Max Points  \
0        Aaron      Lester  axl60952        68.0                       80
1         Adam      Cooper  amc28428        80.0                       80
2         Alec       Curry  axc64717        69.0                       80
3    Alexander   Rodriguez  akr14831        50.0                       80
4        Amber     Daniels  axd11293        54.0                       80
..         ...         ...       ...         ...                      ...
145     Travis  Washington  txw75701        64.0                       80
146       Troy     Raymond  tbr17292        50.0                       80
147   Victoria        Boyd  vkb66346        58.0                       80
148    William      Daniel  wad63934        48.0                       80
149      Woody     Barrera  wxb12345        55.0                       80

    Homework 1 - Submission Time  Homework 2  Homework 2 - Max Points  \
0      2019-08-29 08:56:02-07:00          74                       80
1      2019-08-29 08:56:02-07:00          78                       80
2      2019-08-29 08:56:02-07:00          76                       80
3      2019-08-29 08:56:02-07:00          54                       80
4      2019-08-29 08:56:02-07:00          57                       80
..                           ...         ...                      ...
145    2019-08-29 08:56:02-07:00          67                       80
146    2019-08-29 08:56:02-07:00          59                       80
147    2019-08-29 08:56:02-07:00          61                       80
148    2019-08-29 08:56:02-07:00          60                       80
149    2019-08-29 08:56:02-07:00          62                       80

    Homework 2 - Submission Time  Homework 3  ...  Exam 2 Exam 2 - Max Points  \
0      2019-09-05 08:56:02-07:00          77  ...      63                 100
1      2019-09-05 08:56:02-07:00          78  ...      63                 100
2      2019-09-05 08:56:02-07:00          66  ...      78                 100
3      2019-09-05 08:56:02-07:00          74  ...      97                 100
4      2019-09-05 08:56:02-07:00          77  ...      95                 100
..                           ...         ...  ...     ...                 ...
145    2019-09-05 08:56:02-07:00          56  ...      74                 100
146    2019-09-05 08:56:02-07:00          79  ...      67                 100
147    2019-09-05 08:56:02-07:00          75  ...      93                 100
148    2019-09-05 08:56:02-07:00          72  ...      91                 100
149    2019-09-05 08:56:02-07:00          73  ...      62                 100

      Exam 2 - Submission Time  Exam 3 Exam 3 - Max Points  \
0    2019-11-08 12:30:07-07:00      68                 100
1    2019-11-08 12:30:07-07:00      90                 100
2    2019-11-08 12:30:07-07:00      83                 100
3    2019-11-08 12:30:07-07:00      81                 100
4    2019-11-08 12:30:07-07:00      88                 100
..                         ...     ...                 ...
145  2019-11-08 12:30:07-07:00      68                 100
146  2019-11-08 12:30:07-07:00     100                 100
147  2019-11-08 12:30:07-07:00      69                 100
148  2019-11-08 12:30:07-07:00      95                 100
149  2019-11-08 12:30:07-07:00      90                 100

      Exam 3 - Submission Time       ID                          Name  \
0    2019-12-08 12:30:07-07:00  7308367                 Lester, Aaron
1    2019-12-08 12:30:07-07:00  9204701           Cooper, Adam Melvin
2    2019-12-08 12:30:07-07:00  4570025                   Curry, Alec
3    2019-12-08 12:30:07-07:00  1791350  Rodriguez, Alexander Katelyn
4    2019-12-08 12:30:07-07:00  3932938                Daniels, Amber
..                         ...      ...                           ...
145  2019-12-08 12:30:07-07:00  2213589            Washington, Travis
146  2019-12-08 12:30:07-07:00  6506766           Raymond, Troy Bryan
147  2019-12-08 12:30:07-07:00  6035936       Boyd, Victoria Kimberly
148  2019-12-08 12:30:07-07:00  7474490        Daniel, William Austin
149  2019-12-08 12:30:07-07:00  1234567            Barrera Jr., Woody

                    Email Address  Section
0           aaron.lester@univ.edu        2
1            adam.cooper@univ.edu        2
2             alec.curry@univ.edu        2
3    alexander.rodriguez@univ.edu        2
4          amber.daniels@univ.edu        2
..                            ...      ...
145    travis.washington@univ.edu        1
146         troy.raymond@univ.edu        3
147        victoria.boyd@univ.edu        2
148       william.daniel@univ.edu        2
149     woody.barrera_jr@univ.edu        1

[150 rows x 46 columns]